parameters:
#    uff_calculator.example.class: Uff\CalculatorBundle\Example

services:
#    uff_calculator.example:
#        class: %uff_calculator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
