instance:
    pattern:  /
    defaults: { _controller: "UffCalculatorBundle:Instance:index" }

instance_show:
    pattern:  /{id}/show
    defaults: { _controller: "UffCalculatorBundle:Instance:show" }

instance_new:
    pattern:  /new
    defaults: { _controller: "UffCalculatorBundle:Instance:new" }

instance_create:
    pattern:  /create
    defaults: { _controller: "UffCalculatorBundle:Instance:create" }
    requirements: { _method: post }

instance_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "UffCalculatorBundle:Instance:edit" }

instance_update:
    pattern:  /{id}/update
    defaults: { _controller: "UffCalculatorBundle:Instance:update" }
    requirements: { _method: post|put }

instance_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "UffCalculatorBundle:Instance:delete" }
    requirements: { _method: post|delete }
