<?php

namespace Uff\CalculatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends EntityRepository
{
}
